# Generated by Django 3.0.3 on 2020-02-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200218_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
